#! /bin/bash

# assume start in devel dir
cd rst
make html
./pause.py

#rm _build/latex/Hands-onPythonTutorial.tex
make latex
./pause.py
cp _build/latex/ProgrammingInCSharp.tex oldtex
./texFix.py _build/latex/ProgrammingInCSharp.tex && 
cd _build/latex && make all-pdf
